In [112]:
from tqdm import tqdm
from tqdm.notebook import tqdm_notebook

ModuleNotFoundError: No module named 'tqdm'

In [106]:
n_seq = np.array([20,50,100])
corr_seq_int = -np.ones((len(n_seq),))
corr_seq_occ = -np.ones((len(n_seq),))
num_rep = 1000

In [107]:
corr_seq_int

array([-1., -1., -1.])

In [108]:
corr_seq_occ

array([-1., -1., -1.])

In [114]:
 np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])